-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_notifiche_eventi_1 ON notifiche_eventi ;
-- DROP INDEX index_pcc_rispedizioni_1 ON pcc_rispedizioni ;
-- DROP INDEX index_pcc_contabilizzazioni_1 ON pcc_contabilizzazioni ;
-- DROP INDEX index_pcc_operazioni_1 ON pcc_operazioni ;
-- DROP INDEX idx_dipart_prop_values_1 ON dipartimenti_prop_values ;
-- DROP INDEX index_dipartimenti_props_1 ON dipartimenti_props ;
-- DROP INDEX index_dipartimenti_1 ON dipartimenti ;
-- DROP INDEX index_utenti_1 ON utenti ;
-- DROP INDEX index_registri_prop_values_1 ON registri_prop_values ;
-- DROP INDEX index_registri_props_1 ON registri_props ;
-- DROP INDEX index_registri_1 ON registri ;
-- DROP INDEX index_protocolli_1 ON protocolli ;
-- DROP INDEX index_enti_1 ON enti ;
-- DROP INDEX index_comunicazioni_sdi_1 ON comunicazioni_sdi ;
-- DROP INDEX idx_cp_denominazione_fatt ON fatture ;
-- DROP INDEX index_fatture_1 ON fatture ;
-- DROP INDEX index_decorrenza_termini_1 ON decorrenza_termini ;
-- DROP INDEX idx_cp_denominazione ON lotti ;
-- DROP INDEX index_lotti_1 ON lotti ;
DROP TABLE notifiche_eventi;
DROP TABLE pcc_notifiche;
DROP TABLE pcc_rispedizioni;
DROP TABLE pcc_pagamenti;
DROP TABLE pcc_scadenze;
DROP TABLE pcc_contabilizzazioni;
DROP TABLE pcc_utenti_operazioni;
DROP TABLE dipartimenti_operazioni;
DROP TABLE pcc_operazioni;
DROP TABLE utenti_dipartimenti;
DROP TABLE dipartimenti_prop_values;
DROP TABLE dipartimenti_props;
DROP TABLE dipartimenti;
DROP TABLE esito_committente;
DROP TABLE utenti;
DROP TABLE registri_prop_values;
DROP TABLE registri_props;
DROP TABLE registri;
DROP TABLE protocolli;
DROP TABLE enti;
DROP TABLE metadati;
DROP TABLE comunicazioni_sdi;
DROP TABLE allegati;
DROP TABLE fatture;
DROP TABLE pcc_errori_elaborazione;
DROP TABLE tracce_trasmissioni_esiti;
DROP TABLE pcc_tracce_trasmissioni;
DROP TABLE pcc_tracce;
DROP TABLE decorrenza_termini;
DROP TABLE lotti;
