-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_dipart_prop_values_1;
-- DROP INDEX index_dipartimenti_props_1;
-- DROP INDEX index_dipartimenti_1;
-- DROP INDEX index_utenti_1;
-- DROP INDEX index_registri_prop_values_1;
-- DROP INDEX index_registri_props_1;
-- DROP INDEX index_registri_1;
-- DROP INDEX index_enti_1;
-- DROP INDEX idx_cp_denominazione_fatt;
-- DROP INDEX index_fatture_1;
-- DROP INDEX index_decorrenza_termini_1;
-- DROP INDEX idx_cp_denominazione;
-- DROP INDEX index_lotti_1;
DROP TABLE utenti_dipartimenti;
DROP TABLE dipartimenti_prop_values;
DROP TABLE dipartimenti_props;
DROP TABLE dipartimenti;
DROP TABLE esito_committente;
DROP TABLE utenti;
DROP TABLE registri_prop_values;
DROP TABLE registri_props;
DROP TABLE registri;
DROP TABLE enti;
DROP TABLE allegati;
DROP TABLE fatture;
DROP TABLE decorrenza_termini;
DROP TABLE lotti;
