-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX idx_dipart_prop_values_1 ON dipartimenti_prop_values ;
-- DROP INDEX index_dipartimenti_props_1 ON dipartimenti_props ;
-- DROP INDEX index_dipartimenti_1 ON dipartimenti ;
-- DROP INDEX index_utenti_1 ON utenti ;
-- DROP INDEX index_registri_prop_values_1 ON registri_prop_values ;
-- DROP INDEX index_registri_props_1 ON registri_props ;
-- DROP INDEX index_registri_1 ON registri ;
-- DROP INDEX index_enti_1 ON enti ;
-- DROP INDEX idx_cp_denominazione_fatt ON fatture ;
-- DROP INDEX index_fatture_1 ON fatture ;
-- DROP INDEX index_decorrenza_termini_1 ON decorrenza_termini ;
-- DROP INDEX idx_cp_denominazione ON lotti ;
-- DROP INDEX index_lotti_1 ON lotti ;
DROP TABLE utenti_dipartimenti;
DROP TABLE dipartimenti_prop_values;
DROP TABLE dipartimenti_props;
DROP TABLE dipartimenti;
DROP TABLE esito_committente;
DROP TABLE utenti;
DROP TABLE registri_prop_values;
DROP TABLE registri_props;
DROP TABLE registri;
DROP TABLE enti;
DROP TABLE allegati;
DROP TABLE fatture;
DROP TABLE decorrenza_termini;
DROP TABLE lotti;
