-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_notifiche_eventi_1;
-- DROP INDEX index_pcc_rispedizioni_1;
-- DROP INDEX index_pcc_contabilizzazioni_1;
-- DROP INDEX index_pcc_operazioni_1;
-- DROP INDEX idx_dipart_prop_values_1;
-- DROP INDEX index_dipartimenti_props_1;
-- DROP INDEX index_dipartimenti_1;
-- DROP INDEX index_utenti_1;
-- DROP INDEX index_registri_prop_values_1;
-- DROP INDEX index_registri_props_1;
-- DROP INDEX index_registri_1;
-- DROP INDEX index_protocolli_1;
-- DROP INDEX index_enti_1;
-- DROP INDEX index_comunicazioni_sdi_1;
-- DROP INDEX idx_cp_denominazione_fatt;
-- DROP INDEX index_fatture_1;
-- DROP INDEX index_decorrenza_termini_1;
-- DROP INDEX idx_cp_denominazione;
-- DROP INDEX index_lotti_1;
DROP TABLE notifiche_eventi;
DROP TABLE pcc_notifiche;
DROP TABLE pcc_rispedizioni;
DROP TABLE pcc_pagamenti;
DROP TABLE pcc_scadenze;
DROP TABLE pcc_contabilizzazioni;
DROP TABLE pcc_utenti_operazioni;
DROP TABLE dipartimenti_operazioni;
DROP TABLE pcc_operazioni;
DROP TABLE utenti_dipartimenti;
DROP TABLE dipartimenti_prop_values;
DROP TABLE dipartimenti_props;
DROP TABLE dipartimenti;
DROP TABLE esito_committente;
DROP TABLE utenti;
DROP TABLE registri_prop_values;
DROP TABLE registri_props;
DROP TABLE registri;
DROP TABLE protocolli;
DROP TABLE enti;
DROP TABLE metadati;
DROP TABLE comunicazioni_sdi;
DROP TABLE allegati;
DROP TABLE fatture;
DROP TABLE pcc_errori_elaborazione;
DROP TABLE tracce_trasmissioni_esiti;
DROP TABLE pcc_tracce_trasmissioni;
DROP TABLE pcc_tracce;
DROP TABLE decorrenza_termini;
DROP TABLE lotti;
