-- Gli indici vengono eliminati automaticamente una volta eliminata la tabella
-- DROP INDEX index_notifiche_eventi_1;
-- DROP INDEX index_pcc_rispedizioni_1;
-- DROP INDEX index_pcc_contabilizzazioni_1;
-- DROP INDEX index_pcc_operazioni_1;
-- DROP INDEX idx_dipart_prop_values_1;
-- DROP INDEX index_dipartimenti_props_1;
-- DROP INDEX index_dipartimenti_1;
-- DROP INDEX index_utenti_1;
-- DROP INDEX index_registri_prop_values_1;
-- DROP INDEX index_registri_props_1;
-- DROP INDEX index_registri_1;
-- DROP INDEX index_protocolli_1;
-- DROP INDEX index_enti_1;
-- DROP INDEX index_comunicazioni_sdi_1;
-- DROP INDEX idx_cp_denominazione_fatt;
-- DROP INDEX index_fatture_1;
-- DROP INDEX index_decorrenza_termini_1;
-- DROP INDEX idx_cp_denominazione;
-- DROP INDEX index_lotti_1;
DROP TABLE notifiche_eventi_init_seq;
DROP TABLE notifiche_eventi;
DROP TABLE pcc_notifiche_init_seq;
DROP TABLE pcc_notifiche;
DROP TABLE pcc_rispedizioni_init_seq;
DROP TABLE pcc_rispedizioni;
DROP TABLE pcc_pagamenti_init_seq;
DROP TABLE pcc_pagamenti;
DROP TABLE pcc_scadenze_init_seq;
DROP TABLE pcc_scadenze;
DROP TABLE pcc_contabilizzazioni_init_seq;
DROP TABLE pcc_contabilizzazioni;
DROP TABLE pcc_utenti_operazioni_init_seq;
DROP TABLE pcc_utenti_operazioni;
DROP TABLE dipartimenti_operazioni_init_seq;
DROP TABLE dipartimenti_operazioni;
DROP TABLE pcc_operazioni_init_seq;
DROP TABLE pcc_operazioni;
DROP TABLE utenti_dipartimenti_init_seq;
DROP TABLE utenti_dipartimenti;
DROP TABLE dipartimenti_prop_values_init_seq;
DROP TABLE dipartimenti_prop_values;
DROP TABLE dipartimenti_props_init_seq;
DROP TABLE dipartimenti_props;
DROP TABLE dipartimenti_init_seq;
DROP TABLE dipartimenti;
DROP TABLE esito_committente_init_seq;
DROP TABLE esito_committente;
DROP TABLE utenti_init_seq;
DROP TABLE utenti;
DROP TABLE registri_prop_values_init_seq;
DROP TABLE registri_prop_values;
DROP TABLE registri_props_init_seq;
DROP TABLE registri_props;
DROP TABLE registri_init_seq;
DROP TABLE registri;
DROP TABLE protocolli_init_seq;
DROP TABLE protocolli;
DROP TABLE enti_init_seq;
DROP TABLE enti;
DROP TABLE metadati_init_seq;
DROP TABLE metadati;
DROP TABLE comunicazioni_sdi_init_seq;
DROP TABLE comunicazioni_sdi;
DROP TABLE allegati_init_seq;
DROP TABLE allegati;
DROP TABLE fatture_init_seq;
DROP TABLE fatture;
DROP TABLE pcc_errori_elaborazione_init_seq;
DROP TABLE pcc_errori_elaborazione;
DROP TABLE tracce_trasmissioni_esiti_init_seq;
DROP TABLE tracce_trasmissioni_esiti;
DROP TABLE pcc_tracce_trasmissioni_init_seq;
DROP TABLE pcc_tracce_trasmissioni;
DROP TABLE pcc_tracce_init_seq;
DROP TABLE pcc_tracce;
DROP TABLE decorrenza_termini_init_seq;
DROP TABLE decorrenza_termini;
DROP TABLE lotti_init_seq;
DROP TABLE lotti;
DROP SEQUENCE seq_notifiche_eventi;
DROP SEQUENCE seq_pcc_notifiche;
DROP SEQUENCE seq_pcc_rispedizioni;
DROP SEQUENCE seq_pcc_pagamenti;
DROP SEQUENCE seq_pcc_scadenze;
DROP SEQUENCE seq_pcc_contabilizzazioni;
DROP SEQUENCE seq_pcc_utenti_operazioni;
DROP SEQUENCE seq_dipartimenti_operazioni;
DROP SEQUENCE seq_pcc_operazioni;
DROP SEQUENCE seq_utenti_dipartimenti;
DROP SEQUENCE seq_dipartimenti_prop_values;
DROP SEQUENCE seq_dipartimenti_props;
DROP SEQUENCE seq_dipartimenti;
DROP SEQUENCE seq_esito_committente;
DROP SEQUENCE seq_utenti;
DROP SEQUENCE seq_registri_prop_values;
DROP SEQUENCE seq_registri_props;
DROP SEQUENCE seq_registri;
DROP SEQUENCE seq_protocolli;
DROP SEQUENCE seq_enti;
DROP SEQUENCE seq_metadati;
DROP SEQUENCE seq_comunicazioni_sdi;
DROP SEQUENCE seq_allegati;
DROP SEQUENCE seq_fatture;
DROP SEQUENCE seq_pcc_errori_elaborazione;
DROP SEQUENCE seq_tracce_trasmissioni_esiti;
DROP SEQUENCE seq_pcc_tracce_trasmissioni;
DROP SEQUENCE seq_pcc_tracce;
DROP SEQUENCE seq_decorrenza_termini;
DROP SEQUENCE seq_lotti;
