/*
 * ProxyFatturaPA - Gestione del formato Fattura Elettronica 
 * http://www.gov4j.it/fatturapa
 * 
 * Copyright (c) 2014-2020 Link.it srl (http://link.it). 
 * Copyright (c) 2014-2020 Provincia Autonoma di Bolzano (http://www.provincia.bz.it/). 
 * 
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License version 3, as published by
 * the Free Software Foundation.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 *
 */
//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.10.09 at 03:34:31 PM CEST 
//


package org.govmix.proxy.fatturapa.notificaesitocommittente;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for MotivoRifiuto.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="MotivoRifiuto">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="EC01"/>
 *     &lt;enumeration value="EC02"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "MotivoRifiuto")
@XmlEnum
public enum MotivoRifiuto {


    /**
     * MR01 - Soggetto destinatario errato
     * 
     */
    @XmlEnumValue("MR01")
    MR_01("MR01"),
    /**
     * MR02 - Omesso o errato CIG o CUP
     * 
     */
    @XmlEnumValue("MR02")
    MR_02("MR02"),
    /**
     * MR03 - Omesso o errato numero e data dell’atto d’impegno
     * 
     */
    @XmlEnumValue("MR03")
    MR_03("MR03");
    
    private final String value;

    MotivoRifiuto(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static MotivoRifiuto fromValue(String v) {
        for (MotivoRifiuto c: MotivoRifiuto.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
